/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Running Application
 #	author : miyako
 #	2013/08/01
 #
 # --------------------------------------------------------------------------------*/



// --- App
void App_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void App_TERMINATE(sLONG_PTR *pResult, PackagePtr pParams);
void App_FORCE_TERMINATE(sLONG_PTR *pResult, PackagePtr pParams);
void App_Is_active(sLONG_PTR *pResult, PackagePtr pParams);
void App_ACTIVATE(sLONG_PTR *pResult, PackagePtr pParams);
void App_Get_icon(sLONG_PTR *pResult, PackagePtr pParams);
void App_HIDE(sLONG_PTR *pResult, PackagePtr pParams);
void App_SHOW(sLONG_PTR *pResult, PackagePtr pParams);
void App_Is_hidden(sLONG_PTR *pResult, PackagePtr pParams);
