/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Running Application
 #	author : miyako
 #	2015/08/18
 #
 # --------------------------------------------------------------------------------*/



// --- App
void App_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void App_TERMINATE(sLONG_PTR *pResult, PackagePtr pParams);
void App_FORCE_TERMINATE(sLONG_PTR *pResult, PackagePtr pParams);
void App_Is_active(sLONG_PTR *pResult, PackagePtr pParams);
void App_ACTIVATE(sLONG_PTR *pResult, PackagePtr pParams);
void App_Get_icon(sLONG_PTR *pResult, PackagePtr pParams);
void App_HIDE(sLONG_PTR *pResult, PackagePtr pParams);
void App_SHOW(sLONG_PTR *pResult, PackagePtr pParams);
void App_Is_hidden(sLONG_PTR *pResult, PackagePtr pParams);
void App_Get_path(sLONG_PTR *pResult, PackagePtr pParams);
void App_Get_localized_name(sLONG_PTR *pResult, PackagePtr pParams);

#define DEFAULT_ICON_SIZE 1024
#define APP_CURRENT_APPLICATION @"__CURRENT__"
NSRunningApplication *_getApp(C_TEXT& appBundleIdentifier);