/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Running-Application.h
 #	source generated by 4D Plugin Wizard
 #	Project : Running Application
 #	author : miyako
 #	2020/09/03
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_RUNNING_APPLICATION_H
#define PLUGIN_RUNNING_APPLICATION_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"
#include "C_LONGINT.h"
#include "ARRAY_TEXT.h"
#include "ARRAY_LONGINT.h"

#pragma mark -

void App_LIST(PA_PluginParameters params);
void App_TERMINATE(PA_PluginParameters params);
void App_FORCE_TERMINATE(PA_PluginParameters params);
void App_Is_active(PA_PluginParameters params);
void App_ACTIVATE(PA_PluginParameters params);
void App_Get_icon(PA_PluginParameters params);
void App_HIDE(PA_PluginParameters params);
void App_SHOW(PA_PluginParameters params);
void App_Is_hidden(PA_PluginParameters params);
void App_Get_path(PA_PluginParameters params);
void App_Get_localized_name(PA_PluginParameters params);
void App_Find_path(PA_PluginParameters params);

#define DEFAULT_ICON_SIZE 1024
#define APP_CURRENT_APPLICATION @"__CURRENT__"
NSRunningApplication *_getApp(C_TEXT& appBundleIdentifier);

#endif /* PLUGIN_RUNNING_APPLICATION_H */
